---

- name: Create directories for CLion
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ clion_install_directory }}"
  - "{{ clion_desktop_file_location | dirname }}"

- name: Install CLion
  unarchive:
    copy: no
    src: "{{ clion_download_url}}"
    dest: "{{ clion_install_directory }}"
    creates: "{{ clion_location }}/bin/clion.sh"

# TODO: creates?
- name: Install CLion Plugins
  unarchive:
    copy: no
    src: "{{ clion_plugin_download_mirror }}{{ item }}"
    dest: "{{ clion_location }}/plugins"
  with_items: "{{ clion_plugins }}"

- name: Create CLion desktop entry
  template:
    src: clion.desktop.j2
    dest: "{{ clion_desktop_file_location }}"
